#!/bin/bash

COMMAND=$1
export PORT=1234

function initialize() {
  echo "Linking openapi-fastify"
  npm link openapi-fastify
  npx tsx tests/integration/app/serve.ts &
  echo "Starting Server w/ Port $PORT"
}
function cleanup() {
  PID=$(lsof -t -i :$PORT)
  echo "PORT: $PORT / PID: $PID"
  if [ -n "$PID" ]; then
    echo "Killing Server w/ PID: $PID"
    kill -9 "$PID"
  fi
  echo "Unlinking openapi-fastify"
  npm unlink openapi-fastify
}
function check-cleanup(){
  PID=$(lsof -t -i :$PORT)
  if [ -n "$PID" ]; then
    echo "Server is still running w/ PID: $PID"
  else 
    echo "✅ Cleanup successful"
  fi
}

main(){
  initialize
  npx jest
  cleanup
}

if [ "$COMMAND" == "cleanup" ]; then
  cleanup
elif [ "$COMMAND" == "check-cleanup" ]; then
  check-cleanup
else
  main
fi




# lsof -t -i :$PORT